### ISSUE TITLE
Error: Could not find connect.xml. 

### ISSUE THREAD

**Issue by srinivast-9** [HCK-CI/toolsHCK#17]
1. Is connect.xml created manually?
2. What are the contents of connect.xml?

**Comment by YanVugenfirer** [comment]
Hello,

When do you this error? Can you please elaborate on the steps?

Thanks,
Yan.

**Comment by Basils** [comment]
> 1. Is connect.xml created manually?
No, connect.xml is a file generated during HLK Controller installation.

> 2. What are the contents of connect.xml?
it contains the name of HLK controller server and HLK db name.

Are you using HLK Studio standalone installation? if so please install Controller + Studio version.

**Comment by kostyanf14** [comment]
can't reproduce
