### ISSUE TITLE
listtest or listtestresults are not showing "Functional" and "Reliability" test cases

### ISSUE THREAD

**Issue by GirishTV** [HCK-CI/toolsHCK#18]
listtest or listtestresults are not showing "Functional" and "Reliability" test cases
its only showing "Certification" related test cases.
test cases: DF - Reboot Restart with IO During (Reliability), DF - Concurrent Hardware And Operating System (CHAOS) Test (Reliability)

And 
 <TestCollectionRecord Name="**DF - Reboot restart with IO before and after (Functional)**" Guid="99c61fa9-e0eb-43ea-a5fc-db5c3cbd9239" EstimatedRuntimeInSeconds="240" TargetName="Adaptec SmartHBA 2100-8i Controller" TargetId="PCI\VEN_9005&amp;DEV_028F&amp;SUBSYS_09009005&amp;REV_01" TargetType="Device" HckBuildVersion="8.100.9600.27024" OsPlatform="Windows v6.3 Client x64" TestPassIdentifier="TP002">
    <ContentLevelSet>Functional</ContentLevelSet>
    <ScheduleOptionSet>Distributable</ScheduleOptionSet>
    <ScheduleOptionSet>MultipleDevices</ScheduleOptionSet>
    <ScheduleOptionSet>SpecialConfiguration</ScheduleOptionSet>
    <FeatureMapped>Device.DevFund.Reliability</FeatureMapped>
  </TestCollectionRecord>

**Comment by Basils** [comment]
Hi,

The tests showed as the output of "listtest" and "listtestresult",
should be the same as the test list in WHLK Studio.
There are multiple settings that might affect this list, such as playlist and exposed features of the tested device.
examples:
1. for HLK1809 server version DF - Concurrent Hardware And Operating System (CHAOS) Test is dropped by
the playlist.
2. if you want to run Reliability tests, the tested device should expose "Device.DevFund.Reliability" feature.
*you can use device "Power Button" as a test case.

Can you share more information about your setup? which features does the device you are testing expose?

Thanks,
Basil

**Comment by GirishTV** [comment]
Hi @Basils ,

There are many Reliability & Functional test cases to be tested as per requirement. But toolsHCK is unable to load those test cases.
Is there any way to add support in "toolsHCK.ps1" script, to list all those test cases. So that i can run those test from toolsHCK.ps1.

-Girish

**Comment by kostyanf14** [comment]
Hi @GirishTV,

I reviewed the source of `listtest` and `listtestresults` functions. There are no filters. 

Can you please provide complete steps to reproduce?
1. What Windows version is installed on the Studio machine, on the Client machine?
1. What device you add as a target?
1. What full command (with arguments) do you run in toolsHCK?
1. What test is shown in HLKStudio UI, but is missing in toolsHCK `listtest` output?

Thanks,
Kostiantyn

**Comment by GirishTV** [comment]
Hi @kostyanf14 

What Windows version is installed on the Studio machine, on the Client machine?
**>> HLK: Windows Server 2012 Standard
         Client: Windows Microsoft Windows Server 2012 R2 Datacenter** 

What device you add as a target?
**>>Storage controller **
What full command (with arguments) do you run in toolsHCK?
Queue Test:
>>**queuetest** 779dee1a-dfe5-4343-ab48-ac6bfb51d45c "PCI\VEN_9005&DEV_028F&SUBSYS_09009005&REV_01\4&37D550F1&0&00E1" CERT_BLR_9_Bootable_2021-06-25T10-12-41-41_2021-06-25T10-13-31-46 CERT_BLR_9 CERT_BLR_9_Bootable
WARNING: Didn't find a test with the id given.

**List test Result**:
listtestresults 779dee1a-dfe5-4343-ab48-ac6bfb51d45c"PCI\VEN_9005&DEV_028F&SUBSYS_09009005&REV_01\4&37D550F1&0&00E1" CERT_BLR_9_Bootable_2021-06-25T10-12-41-41_2021-06-25T10-13-31-46 CERT_BLR_9 CERT_BLR_9_Bootable
WARNING: Didn't find a test with the id given.


_Test id : 779dee1a-dfe5-4343-ab48-ac6bfb51d45c
Test case: DF - PNP DIF Remove Device Test (Functional)
PCI ID of Storage controller: PCI\VEN_9005&DEV_028F&SUBSYS_09009005&REV_01\4&37D550F1&0&00E1
Project Name: CERT_BLR_9_Bootable_2021-06-25T10-12-41-41_2021-06-25T10-13-31-46
Machine Name: CERT_BLR_9 
Pool name: CERT_BLR_9_Bootable_


What test is shown in HLKStudio UI, but is missing in toolsHCK listtest output?
**>> DF - PNP DIF Remove Device Test (Functional)
         DF - Concurrent Hardware And Operating System (CHAOS) Test (Reliability)
and many Reliability & Functional test cases**

Thanks,
Girish

**Comment by kostyanf14** [comment]
moved to https://github.com/HCK-CI/rtoolsHCK/issues/54
