### ISSUE TITLE
need support to send power strip details (apc ip & port number) via this script for Flush test in 'queuetest' option

### ISSUE THREAD

**Issue by GirishTV** [HCK-CI/toolsHCK#20]
As per test details https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/2dec1f67-b506-4434-8bdf-763147ad8f0b

Setup required for the test: Connect a power distribution unit (PDU), controllable via SNMP, to the HLK test machine.

Power strip should have a valid IP address associated as the test uses both the IP address and the port to initiate sudden power loss.

Power strip can be connected locally/remotely to machine, please see power strip manual for configuration details.

Currently i need to open studio tool and enter APC details  manually. 
Hence, need support to send power strip details via this script for Flush test in 'queuetest' option.

![image](https://user-images.githubusercontent.com/79100062/114691686-9004e700-9d35-11eb-8327-be59ff566227.png)

Flush test: Parameters (IP,OID,Oulet,Community)

**Comment by YanVugenfirer** [comment]
Hello @GirishTV, are you using auto-hck to test the physical device?
If not - MS waived the need to connect PDU for paravirtualized devices.

Best regards,
Yan.

**Comment by GirishTV** [comment]
Hi Yan,
I am testing Flush test on WIN2019, HLK Studio requires APC details to Power off & power on while running flush test. I am able to provide manually but im unable to provide from command line. I have use below command but still not working. 

CMD: PS C:\Program Files (x86)\Windows Kits\10\Hardware Lab Kit\Studio> .\hckexecutionengine.exe /Project "C:\Users\Administrator\Desktop\win10-408i\pdef.xml" /RunCollection /Parameter IP="10.187.137.106" /Parameter OID=".1.3.6.1.4.1.318.1.1.12.3.3.1.1.4" /Parameter Outlet="7" /Parameter Community="private"


Note: im not using auto-hck to test this.
-Girish

**Comment by kostyanf14** [comment]
Hi @YanVugenfirer,

It looks like we need to implement adding parameters for the specific test in the queue_test function.

HLK Studio has an API call for this: https://docs.microsoft.com/en-us/windows-hardware/test/hlk/api/testsetparameter-method--target-string-string-parametersetasdefault-

Best wishes,
Konstantin

**Comment by GirishTV** [comment]
Hi @YanVugenfirer  & @kostyanf14 ,
Can you please implement this new parameter in code and let me know. 

Thanks,
Girish

**Comment by YanVugenfirer** [comment]
Hi @GirishTV,

This is a low-priority feature for us. So it will enter our queue of tasks as best effort.
If you need to expedite the development please contact me.


Best regards,
Yan.

**Comment by GirishTV** [comment]
HI @YanVugenfirer ,
No problem. I will be more happy if you release code as early as possible. I Will be waiting for the fix.

Thanks,
Girish

**Comment by kostyanf14** [comment]
moved to https://github.com/HCK-CI/rtoolsHCK/issues/53
