### ISSUE TITLE
Need support to upload playlist from toolsHCK.ps1 code

### ISSUE THREAD

**Issue by GirishTV** [HCK-CI/toolsHCK#21]
Need support to upload playlist from toolsHCK.ps1 code, new option request.

-Girish

**Comment by YanVugenfirer** [comment]
@GirishTV We have the ability to upload and apply the playlist today. 
You can also blacklist additional tests in configuration json. 

Am I missing something?

Best regards,
Yan.

**Comment by GirishTV** [comment]
Hi @YanVugenfirer ,
We can list test cases in "listtests" by giving input playlist. But that is not reflecting in HLK Studio tool. Still Unselected tests are showing in HLK studio. I want option like, if im applying playlist that has to be reflect in HLK studio.

Thanks
Girish

**Comment by kostyanf14** [comment]
@GirishTV Please check the lattest version. We add `loadplaylist` command, which loads the playlist into HLK studio.

Best regards,
Konstantin.
