### ISSUE TITLE
Add support for Add/Modify features

### ISSUE THREAD

**Issue by GirishTV** [HCK-CI/toolsHCK#23]
HLK loads default features and its test cases on HLK. But need support to add/modify features after creating project target.

![image](https://user-images.githubusercontent.com/79100062/130430001-b64af470-fed5-4566-a661-050fd9ee0290.png)

![image](https://user-images.githubusercontent.com/79100062/130429842-6db708a3-30ea-4285-8557-af8a43fbfca1.png)

Feature required: Device.Storage.Controller.AzureStack. 
Once the above feature is loaded. its related test cases will appear in list tests.

-Girish

**Comment by kostyanf14** [comment]
moved to https://github.com/HCK-CI/rtoolsHCK/issues/52
