### ISSUE TITLE
Is it possible to apply a playlist to the automatically generated hlkx

### ISSUE THREAD

**Issue by zjmletang** [HCK-CI/toolsHCK#27]
The problem is that AutoHCK generates HLKX files that display test items beyond the specified playlist. This results in Microsoft rejecting our WHCP certification submission during manual review, as they believe that the unexecuted test items (since these test items are not included in the playlist) lack errata, leading to a refusal to sign our certification

**Comment by kostyanf14** [comment]
Fixed in https://github.com/HCK-CI/toolsHCK/commit/17f73bf061645ecb4827df6d7e621a2a49ead3e7 and https://github.com/HCK-CI/toolsHCK/commit/2d1591cdeda03463eb0e5de3ece2746f676cdbb7
